import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { ArrowDownRight, ArrowUpRight, ChevronRight, Linkedin, Mail } from "lucide-react";
import portrait from "@/assets/portfolio/0918_封面定图.jpg";

const reveal = { initial:{opacity:0,y:22}, whileInView:{opacity:1,y:0}, viewport:{once:true,margin:"-60px"}, transition:{duration:.6} };

function Carousel({images, label, contain=false}:{images:string[];label:string;contain?:boolean}){
  const [active,setActive]=useState(0);
  useEffect(()=>{const id=setInterval(()=>setActive(v=>(v+1)%images.length),3200);return()=>clearInterval(id)},[images.length]);
  return <div className={`carousel paper-stack ${contain?'contain':''}`} aria-label={`${label} photo gallery`}>
    {images.map((src,i)=>{const offset=(i-active+images.length)%images.length;return <div key={src} className={`photo-sheet ${offset===0?"active":""}`} style={{zIndex:images.length-offset,transform:`translateX(${Math.min(offset,3)*13}px) translateY(${Math.min(offset,3)*5}px) rotate(${Math.min(offset,3)*.7}deg)`,opacity:offset<4?1:0}}><img src={src} alt={`${label} ${i+1}`}/></div>})}
    <button className="carousel-next" onClick={()=>setActive(v=>(v+1)%images.length)} aria-label="Show next image"><ChevronRight size={20}/></button>
    <div className="carousel-dots">{images.map((_,i)=><button key={i} className={i===active?"active":""} onClick={()=>setActive(i)} aria-label={`Show image ${i+1}`}/>)}</div>
  </div>
}

const selectedWork=[
 {no:"01",company:"TikTok Shop",title:"Turning market signals into commercial action",text:"Worked across European e-commerce operations, bringing together market evidence, seller perspectives and performance data to support decisions in a fast-moving, cross-functional environment.",tag:"Commercial Strategy · Europe",images:["/gallery/tt4.jpg","/gallery/tt3.jpg","/gallery/tt1.png","/gallery/tt2.jpg"]},
 {no:"02",company:"Kearney",title:"Finding the answer inside 250,000+ data points",text:"Combined spatial data, expert interviews and structured analysis to assess retail network opportunities—translating a complex evidence base into clear recommendations for senior stakeholders.",tag:"Strategy & Analytics · China",images:["/gallery/kearney.png","/gallery/kearney-photo.jpg"]},
 {no:"03",company:"Volkswagen Group China",title:"Building clarity into complex operations",text:"Designed business-intelligence workflows and decision tools across large operational datasets, helping teams move from manual reporting towards faster, more consistent resource decisions.",tag:"Business Intelligence · China",images:["/gallery/vw1.jpg","/gallery/vw2.jpg","/gallery/vw3.jpg","/gallery/vw4.jpg"]},
 {no:"04",company:"Capital Markets",title:"Connecting financial evidence with investor judgement",text:"Supported IPO execution and equity research across primary and secondary markets—testing commercial evidence, analysing more than 2,000 market data points and translating findings into decision-ready materials.",tag:"Investment Banking · Equity Research",images:["/gallery/cms1.jpg","/gallery/cms2.png","/gallery/cj1.jpg","/gallery/cj2.jpg"]}
];
const experience=[
 {no:"01",company:"TikTok Shop",role:"Business Planning, Operations & Strategic Projects",mark:"TikTok Shop",logo:"/gallery/tiktok-logo.jpg"},
 {no:"02",company:"Kearney",role:"Strategy Analyst",mark:"KEARNEY",logo:"/gallery/kearney.png"},
 {no:"03",company:"Volkswagen Group China",role:"Finance Controlling Analyst",mark:"VOLKSWAGEN",logo:"/gallery/vw-logo.png"},
 {no:"04",company:"China Merchants Securities",role:"Investment Banking Analyst — IPO",mark:"CMS",logo:"/gallery/cms-logo.png"},
 {no:"05",company:"Changjiang Securities",role:"Market Research Analyst — Energy & Utilities",mark:"CJSC",logo:"/gallery/cj-logo.png"},
 {no:"06",company:"Sincere Word Investment Consultancy",role:"Founder & Strategic Investment Analyst",mark:"SINCERE WORD",logo:"/gallery/sw-logo.jpg"}
];
const beyond=[
 {label:"CALLIGRAPHY",title:"Practising patience in every stroke.",text:"Chinese calligraphy keeps me attentive to rhythm, balance and the value of leaving space.",images:[1,2,3,4,5,6,7,8,9].map(x=>`/gallery/calligraphy${x}.jpg`)},
 {label:"MOVEMENT",title:"Consistency over intensity.",text:"Strength training and the outdoors are how I reset, stay grounded and keep going.",images:[1,2,3,4,5,6].map(x=>`/gallery/fitness${x}.jpg`)},
 {label:"COMMUNITY",title:"Giving time, staying connected.",text:"From the British Heart Foundation to professional and bilingual education initiatives, volunteering keeps me close to the communities around me.",images:[1,2,3,4,5,6].map(x=>`/gallery/volunteer${x}.jpg`)}
];

export default function Index(){return <main>
 <nav className="nav"><a href="#top" className="monogram">ZY</a><div><a href="#education">Education</a><a href="#work">Work</a><a href="#experience">Experience</a><a href="#analytical">Analytical range</a><a href="#beyond">Beyond work</a><a href="#contact">Contact</a></div></nav>
 <header id="top" className="hero"><div className="hero-copy"><motion.p className="eyebrow" initial={{opacity:0}} animate={{opacity:1}}>STRATEGY · ANALYTICS · EXECUTION</motion.p><motion.h1 initial={{opacity:0,y:25}} animate={{opacity:1,y:0}}>Zerong <em>(Amanda)</em><br/>Yang</motion.h1><p className="hero-intro">I turn complex evidence into clear commercial decisions—and help teams carry them through.</p><div className="location"><span>Based in London</span><span>Experience across Europe and China</span></div><a href="#work" className="text-link">Selected work <ArrowDownRight size={17}/></a></div><div className="portrait-stage"><motion.div className="portrait-wrap" initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}}><img src={portrait} alt="Zerong Amanda Yang"/><span>London, 2026</span></motion.div></div></header>
 <section className="statement"><motion.div {...reveal}><p className="section-label">PROFILE</p><p className="statement-text">Commercially minded, analytically rigorous and comfortable operating across cultures. My work sits where <strong>strategy meets evidence</strong>: defining the question, structuring the analysis and aligning people around what happens next.</p></motion.div></section>
 <section id="education" className="section education"><div className="education-heading"><p className="section-label">EDUCATION</p><h2>Finance, strategy & the wider economy.</h2></div><div className="education-grid"><article><img src="/gallery/ucl2.jpg" alt="University College London"/><div><span>POSTGRADUATE</span><h3>University College London</h3><p>MSc Economics and Policy of Energy and the Environment</p></div></article><article><img src="/gallery/zuel2.jpg" alt="Zhongnan University of Economics and Law"/><div><span>UNDERGRADUATE</span><h3>Zhongnan University of Economics and Law</h3><p>Bachelor of Economics · Finance & Insurance</p></div></article></div></section>
 <section id="work" className="section work-section"><div className="section-heading"><p className="section-label">SELECTED WORK</p><h2>Four ways I create value.</h2></div><div className="work-list">{selectedWork.map(item=><motion.article className="work-item" key={item.company} {...reveal}><div className="work-no">{item.no}</div><div><p className="work-company">{item.company}</p><h3>{item.title}</h3><p>{item.text}</p><span>{item.tag}</span></div><Carousel images={item.images} label={item.company} contain={item.company==="Kearney"}/></motion.article>)}</div></section>
 <section id="experience" className="section experience-section"><div><p className="section-label">EXPERIENCE</p><h2>Perspective built across industries.</h2><p className="section-lead">Six chapters across technology, consulting, mobility, capital markets and entrepreneurship—each building a different lens on commercial decisions and execution.</p></div><div className="experience-grid">{experience.map(item=><motion.article className="experience-card" key={item.company} {...reveal}><div className={`experience-logo brand-${item.no}`}>{item.logo&&<img src={item.logo} alt={`${item.company} logo`}/>}</div><div className="experience-copy"><span>{item.no}</span><h3>{item.company}</h3><p>{item.role}</p></div></motion.article>)}</div></section>
 <section id="analytical" className="section analytical"><div><p className="section-label">ANALYTICAL RANGE</p><h2>From ambiguity to a decision-ready view.</h2></div><div className="capabilities"><div><span>01</span><h3>Frame</h3><p>Clarify the commercial question and the decision it needs to unlock.</p></div><div><span>02</span><h3>Analyse</h3><p>Build robust models, test assumptions and identify the signal in the noise.</p></div><div><span>03</span><h3>Mobilise</h3><p>Translate insight into a persuasive narrative and practical next steps.</p></div></div><div className="portfolio-grid"><article><p className="section-label">CASE ANALYSIS</p><Carousel images={["/gallery/case1.png","/gallery/case2.png","/gallery/case3.png"]} label="Case analysis" contain/><h3>Structured analysis, clear recommendations.</h3></article><article><p className="section-label">BUSINESS INTELLIGENCE</p><video src="/gallery/bi.mp4" autoPlay muted loop playsInline controls/><h3>Interactive Power BI decision dashboard.</h3></article></div></section>
 <section id="beyond" className="section beyond"><div className="section-heading"><p className="section-label">BEYOND WORK</p><h2>Attention, energy and community.</h2></div><div className="beyond-grid">{beyond.map(item=><article key={item.label}><Carousel images={item.images} label={item.label}/><div><p className="section-label">{item.label}</p><h3>{item.title}</h3><p>{item.text}</p></div></article>)}</div><div className="reading"><p className="section-label">ON MY BOOKSHELF</p><ul><li>《The Brain: The Story of You》 <span>David Eagleman</span></li><li>《How to Win Friends and Influence People》 <span>Dale Carnegie</span></li><li>《The Three-Body Problem》 <span>Liu Cixin</span></li><li>《One Sentence Is Worth a Thousand》 <span>Liu Zhenyun</span></li><li>《Intimate Relationships》 <span>Rowland S. Miller</span></li></ul></div></section>
 <footer id="contact"><div><p className="section-label">LET'S CONNECT</p><h2>Interested in thoughtful work<br/>with tangible outcomes.</h2></div><div className="footer-links"><a href="mailto:zerongyang416@outlook.com"><Mail size={17}/><span><b>Email</b><small>zerongyang416@outlook.com</small></span><ArrowUpRight size={15}/></a><a href="https://www.linkedin.com/in/amandayang416" target="_blank" rel="noreferrer"><Linkedin size={17}/><span><b>LinkedIn</b><small>linkedin.com/in/amandayang416</small></span><ArrowUpRight size={15}/></a></div><p className="motto">What do we say to the God of Death?<br/>Not today.</p><p className="copyright">© {new Date().getFullYear()} Zerong (Amanda) Yang · London</p></footer>
 </main>}
